spring:
   application.name: AUTH SECURITY
   profiles.active: dev
   
server:
   port: 8080
   session-timeout: 0
   
security:
    basic:
        enabled: false

token.secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==

---
spring:
  profiles: dev

ds:

        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        showSql: false
        formatSql: false
        database: SQLSERVER
        url: jdbc:sqlserver://localhost:1433;databaseName=Teste
        username: teste
        password: teste@123

---
spring:
  profiles: prod

ds:

        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        showSql: false
        formatSql: false
        database: SQLSERVER
        url: jdbc:sqlserver://localhost:1433;databaseName=Teste
        username: teste
        password: teste@123
